### ISSUE TITLE
不会用啊，jsp页面在哪？？？

### ISSUE THREAD

**Issue by MlgmXyysd** [L-JINBIN/WeChatPayListener#1]
rt，我是在校初中生，和几个网友组成小喵工作室www.meowcat.tk，写了个html5游戏，想收点赞助，看到这个不错就是不会用

**Comment by L-JINBIN** [comment]
jsp只是判断Running文件是否存在，只是一种检测服务器微信是否在线的思路，并不一定要跟我一样
